### ISSUE TITLE
Initial ToDo List for PlantSEED workshop

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/PlantSEED#1]
- [x] Spin up a second instance of the ModelSEED website **(6/29)**

   (**EDIT**: Neal decided to use a plant/microbe toggle within the same ModelSEED website, keeping all functionality in a single place)
- [x] Re-skin it for PlantSEED **(7/1)**
  * Should users be using RAST or PATRIC auth, considering we wish to use the PATRIC App system? (**EDIT**: We will be using RAST accounts)
- [ ] Replace public genomes page with PlantSEED genomes page **(7/3)**
  * Create PlantSEED PATRIC workspace **(7/1)**
  * Re-generate PlantSEED genomes as PATRIC genomes **(7/2)**
- [ ] Add Genome/Feature viewer **(7/10)**
  * Allow for sub-object fetching within workspace API **(7/10)**

  (**EDIT**: Sub-object fetching will likely not be enabled in time for the workshop. This will mean that genome viewing/editing will be slow, but, for the purposes of the workshop, this will be fine.)

  * Enable editing of functional annotation in individual features **(7/13)**
  * Enable use of CompareRegions to perform prokaryotic comparisons **(7/17)**
    
  (**EDIT**: Bob is currently re-developing CompareRegions in JS, and will also be setting up a means of allowing it to read from a similarities object in a PATRIC workspace. This appears to be our best route for implementing this functionality in the ModelSEED webpage)
  (**EDIT**: If CompareRegions does not materialize in time, we will implement a means of viewing pre-computed similarities in a table)

  * Add BLAST functionality **(7/31)**
    * Users should be able to see if the initial annotation is any good
                     (i.e. compare functional annotation with PlantSEED genomes)
    * Users should be able to look for more prokaryotic homologs

  (**EDIT**: We are not going to aim for this functionality for the workshop. Seeing that I have several files from users already, I will perform BLAST with our prokaryotic NR ahead of time, and we'll be able to view the sims in the feature viewer)

- [ ] Add PlantSEED functional annotation viewer **(7/10)**
  * Users can browse the global list of curated functional annotation available in PlantSEED
- [ ] PlantSEED workflow:
  * Add transcripts uploading App that generates PATRIC Genomes **(7/10)**

  (**EDIT**: This functionality will not be released in time for the workshop)

  * Annotate transcripts **(7/10)**
    * View results in Genome/Feature viewer
    * Edit results in Feature viewer
  * Re-construct models **(7/10)**
    * View results in Model viewer
    * Re-reconstruct models if editing done.
  * Run FBA **(7/10)**
    * View results
    * View and edit media?
- [ ] Use of PATRIC App system
  * Check with Bob to see if we can use currently deployed system

**Comment by samseaver** [comment]
A preliminary breakdown of what we need to do to get the Workshop website up and running, dates are in bold, and amenable (within reason). The workshop is August 13th - 14th, so ideally, I'd like to have most things in place by the end of July.

**Comment by samseaver** [comment]
Added todo for sub-object fetching to allow for genome data to be retrieved in sections.
