### ISSUE TITLE
17 Hours TODo

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/PlantSEED#14]
We fly Wednesday at 6:30pm.

Prioritized list.

- [x] 1) **Edit Feature Function!**

- [x] 2) **Users Annotation Page**
  -  Place "Kmer Features" second, and re-name it to Features. Place "Blast Features" third and rename it "Exemplar Hits" (emphasis will be place on the Features first, Exemplars second).
  - Rename first column to "PlantSEED Role"

- [x] 3) **Model Reconstruction**
Under "My Genomes" page, a genome has a "click to reconstruct" text that results in a pop-up. This needs to be a button that reconstructs directly with preset values for media and minimizefluxes.

- [x] 4) **Feature Attributes**
  - The link for Plant similarities identifiers have a missing slash so they don't work.

- [x] 5) **Models**
-  Each PlantSEED model has a copy button for a user to copy to their workspace (will be copy genome button).

- [x] 6) **My Plant Models**
-  List of user plant models under "My Plant Models".

- [x] 7) **Users Annotation Page**
  - The features listed in the two columns need to link to the original feature viewer

- [x] 8) **Users Annotation Page**
  - In any given role, can you highlight (perhaps by using bold or italics) features that are present in both second and third column

- [x] 8b) **FBA Results**
  - For the FBA results table, if FVA is run, the FBAReaction 'class' is set, can we have that in the table listed after "Max"

- [ ] 9) **Annotation**
-  Global Annotations page, I've one tiny request. Is it possible that when sorting the subsystems, the roles without a subsystem (i.e. with a "-" value) are sent to the bottom of the list?

- [ ] 10) **Aliases**
-  Don't have the SEED aliases appear by default, they are not present in user genomes.

- [ ] 11) **Subsystems**
-  Subsystems aren't showing up in a user's feature pages (bug might be mine)

From Chris:
- [x] 12) remove FVA and minflux options
- [ ] 13) "disable" the unintegration of gapfillings

From Neal:
1) register google analytics on plants.theseed.org, if needed.  page flows are currently tracked on modelseed.theseed.org.
2) Add "PlantSEED Genome" or similar to pages that are public data.  I think this may help workflows.

From José:
- [ ] 1) Fix the count for number of FBAs (and probably number of gap-fills as well) 
- [ ] 2) Features page is not loading (throws a page long error) for genomes in "My Plants" (priority?)

**Comment by nconrad** [comment]
1, 2, and 7 have been deployed.

**Comment by samseaver** [comment]
Discussing point 3:

In my opinion, the models aren't gapfilled when they're initially reconstructed. So, the button would call:

ModelReconstruction()

where the parameters are:
genome => /<user>/plantseed/genomes/<genome>
output_path => /<user>/plantseed/models/
output_file => <genome>_Model

**Comment by cshenry** [comment]
I am fine with doing this for the workshop (turning off initial gap filling and initial FBA).
So if you want to turn off gap filling in model reconstruction, you have to call this:

ModelReconstruction({
  genome => <genome>
  output_path => <path>
  output_file => <model name>
  gapfill => 0,
  predict_essentiality => 0
})

**Comment by nconrad** [comment]
the checkboxes above mean deployed

**Comment by nconrad** [comment]
@samseaver, to be safe, could you be more specific about the seed aliases in (10)?  Which page?

Can we get by without (9) for tomorrow?

**Comment by cshenry** [comment]
Neal,

Yeah, I think we get by without 9.

Chris

**Comment by nconrad** [comment]
If the user has visited the my models page, and then goes and copies a plant model, the my models data should update in memory now.  If we want the same sort of thing for reconstruct, we'd need the server to return the same structure as list_models/copy_model.

**Comment by samseaver** [comment]
Chris is fixing issue with recursive copy of genome.

With regards to SEED aliases, user genomes don't have them. If you go to the feature page of a user genome, you'll get 'SEED' listed under aliases, but no value.
