### ISSUE TITLE
24 Hour ToDo for 2016 PlantSEED Workshop

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/PlantSEED#18]
This is purely for the workshop itself, and will be revised again, afterwards, for the paper itself.

1) Transcriptomics Flux Balance Analysis:
- [x] 1. Test back-end tFBA with uploaded expression data for A. thaliana (Chris)
- [x] 2. Implement options for front-end call to tFBA, allowing users to pick dataset/experiment (Neal)
- [ ] 3. Reaction knockout input

2) Model Editing:
- [ ] 1. Implement front-end capability to add or remove a reaction from the model (Neal)
- [ ] 2. Test reaction addition/removal in models (Sam)

3) Annotation:
- [x] 1. Fix get_feature() call in front-end (Neal)
- [x] 2. Fix get_feature() call in back-end (Sam)
- [x] 3. Finish and deploy BLAST function (only to be called intentionally from genomes page; Sam)
- [x] 4. Test editing of feature annotation (Neal and Sam)

4) Sandbox Model:
- [x] 1. Fix Sandbox Model growth in ProbModelSEED (Chris)
- [x] 2. Create fake transcriptomics data for Sandbox Model (Sam)

5) Reference Data:
- [x] 1. Fix exemplars in both reference and user genomes (Sam)
- [x] 2. Re-populate similarities for new Phytozome reference genomes (Sam)
- [x] 3. Implement use of copy_model() function for reference genomes/models (Neal)
- [ ] 4. Funky A. lyrata gene ids (Sam)
- [x] 5. Feature Lookup object needs updating (Sam)

Added by Neal:

6)
- [x] 1. Send "/$path/PlantHeterotrophicMedia" as default to server for reconstruction/fba (neal)
- [x] 2. Use /plantseed/Data/annotation_overview for annotation overview tab (neal)
- [x] 3. Remove media option from model reconstruction
- [ ] 4. Highlight of exemplars missing first row
- [ ] 5. Hide feature aliases
- [ ] 6. Scrolling
- [x] 7. Update genome name at top of genome page

**Comment by nconrad** [comment]
I'll post comments below for anything that is deployed to the test server and let @samseaver use the checkmarks to mean "ready to go".

**Comment by nconrad** [comment]
5.3 deployed

**Comment by nconrad** [comment]
3.1 deployed
